spring.application.name=Jcheckpoint

# Map the local save directory using an environment variable
# ${...} sintax to search external values
# CHECKPOINT_SAVE_PATH: "key" name that springs will looking for
checkpoint.save-path=${CHECKPOINT_SAVE_PATH}

