# Info
app.name=@project.name@
app.version=@project.version@
info.spring.boot.version=${spring-boot.version}

app.storage.local.path=${LOCAL_SAVE_PATH:/home/danielribeiro/.config/retroarch/saves/}

# active storage profile
app.storage.type=sftp

# SFTP config (with fallback)
app.trimui.ip=${TRIMUI_IP:192.168.0.107}
app.trimui.port=${TRIMUI_PORT:2022}
app.trimui.user=${TRIMUI_USER:trimui}
app.trimui.password=${TRIMUI_PASSWORD}

# trimui saves directory
app.trimui.save-path=${TRIMUI_SAVE_PATH:/SDCARD/RetroArch/.retroarch/saves/}

# dynamic extensions
app.trimui.save-extensions=.srm,.sav,.state,.mcr,.rtc,.smd,.md,.gba,.gb,.gbc,.srm,.vmu