# Info
app.name=@project.name@
app.version=@project.version@
info.spring.boot.version=${spring-boot.version}

app.storage.local.path=${LOCAL_SAVE_PATH}

# active storage profile
app.storage.type=sftp

# SFTP config
app.trimui.ip=192.168.0.107
app.trimui.port=2022
app.trimui.user=trimui
app.trimui.password=trimui

# trimui saves directory
app.trimui.save-path=/SDCARD/RetroArch/.retroarch/saves/

# dynamic extensions
app.trimui.save-extensions=.srm,.sav,.state,.mcr,.rtc,.smd,.md,.gba,.gb,.gbc,.srm,.vmu